# Generated by Django 4.2.29 on 2026-03-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('track', models.CharField(default='Default', max_length=100)),
                ('color', models.CharField(blank=True, default='', max_length=7)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
    ]
