# Generated by Django 4.2.29 on 2026-03-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='dependents', to='events.event'),
        ),
    ]
