# Generated by Django 4.2.29 on 2026-03-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_depends_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='percent_complete',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
