# Generated by Django 4.2.30 on 2026-09-19 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_committed_end'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_milestone',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StatusReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateTimeField()),
                ('layout', models.CharField(choices=[('slide', '16:9 slide'), ('handout', 'Portrait handout')], default='slide', max_length=10)),
                ('status', models.CharField(choices=[('on_track', 'On track'), ('at_risk', 'At risk'), ('off_track', 'Off track')], max_length=10)),
                ('status_source', models.CharField(choices=[('rule', 'Derived by rule'), ('override', 'Set by the author')], default='rule', max_length=10)),
                ('override_reason', models.CharField(blank=True, default='', max_length=200)),
                ('rule_fired', models.CharField(blank=True, default='', max_length=200)),
                ('suggested_status', models.CharField(blank=True, choices=[('on_track', 'On track'), ('at_risk', 'At risk'), ('off_track', 'Off track')], default='', max_length=10)),
                ('content', models.JSONField(default=dict)),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_reports', to='projects.project')),
            ],
            options={
                'ordering': ['-as_of', '-id'],
            },
        ),
    ]
