# Generated by Django 4.2.29 on 2026-03-07 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_percent_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='track',
            new_name='category',
        ),
    ]
