# Generated by Django 4.2.30 on 2026-07-12 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_hiddenbuiltintemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_links', to='projects.project')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='projects.team')),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectteam',
            constraint=models.UniqueConstraint(fields=('project', 'team'), name='uniq_project_team'),
        ),
    ]
