# Generated by Django 4.2.30 on 2026-07-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectteam_projectteam_uniq_project_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='EffectiveAccessReport',
            fields=[
            ],
            options={
                'verbose_name': 'Effective access',
                'verbose_name_plural': 'Effective access',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.project',),
        ),
    ]
