# Generated by Django 4.2.30 on 2026-07-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_effectiveaccessreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('commenter', 'Commenter'), ('viewer', 'Viewer')], default='viewer', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectteam',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('commenter', 'Commenter'), ('viewer', 'Viewer')], default='viewer', max_length=10),
        ),
    ]
