# Generated by Django 4.2.30 on 2026-09-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_projectmembership_role_alter_projectteam_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='committed_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
