# Generated by Django 4.2.30 on 2026-09-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_committed_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status_thresholds',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
