# Generated by Django 6.1.1 on 2026-09-20 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_status_thresholds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='count_in_track_record',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source_template_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='source_template_span',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='author_display',
            field=models.CharField(choices=[('name', 'Show my name'), ('anonymous', 'A member')], default='name', max_length=10),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='forked_from_key',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='group',
            field=models.CharField(choices=[('business', 'Business'), ('work', 'Work'), ('hobby', 'Hobby'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='share_notes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='share_todos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='shared_with_teams',
            field=models.ManyToManyField(blank=True, related_name='shared_templates', to='projects.team'),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('teams', 'Shared with teams'), ('instance', 'Everyone on this instance')], default='private', max_length=10),
        ),
        migrations.CreateModel(
            name='TemplateComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(db_index=True, max_length=120)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(db_index=True, max_length=120)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.templatecomment')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['resolved', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(db_index=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'template_key'), name='uniq_template_vote')],
            },
        ),
    ]
