# Generated by Django 6.1.1 on 2026-09-20 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_template_library'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='closeout_dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RunCloseout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(blank=True, choices=[('worked', 'It worked'), ('worked_with_changes', 'It worked, with changes'), ('did_not_work', 'It did not work'), ('stopped', 'We stopped early')], default='', max_length=20)),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cost_currency', models.CharField(blank=True, default='', max_length=3)),
                ('effort_person_days', models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True)),
                ('lesson', models.TextField(blank=True, default='')),
                ('share_figures', models.BooleanField(default=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closeout', to='projects.project')),
            ],
        ),
    ]
