# Generated by Django 6.1.1 on 2026-09-20 13:45

import django.db.models.deletion
from django.db import migrations, models


def keep_earlier_lessons_private(apps, schema_editor):
    """Close-outs written before this migration were made under a dialog that said the lesson is
    "kept with this project". Hold to that: they are not sent to a template's owner."""
    apps.get_model('projects', 'RunCloseout').objects.update(lesson_to_owner=False)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_run_closeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='origin_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_saved_from', to='projects.project'),
        ),
        migrations.AddField(
            model_name='runcloseout',
            name='lesson_to_owner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='runcloseout',
            name='posted_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.templatecomment'),
        ),
        migrations.RunPython(keep_earlier_lessons_private, migrations.RunPython.noop),
    ]
