# Generated by Django 6.1.1 on 2026-09-20 17:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def give_each_closeout_its_own_ref(apps, schema_editor):
    """AddField evaluates the default once, so every existing close-out got the same lesson_ref."""
    RunCloseout = apps.get_model('projects', 'RunCloseout')
    for closeout in RunCloseout.objects.all():
        closeout.lesson_ref = uuid.uuid4()
        closeout.save(update_fields=['lesson_ref'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_closeout_lessons_and_origin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='runcloseout',
            name='lesson_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='runcloseout',
            name='lesson_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='runcloseout',
            name='lesson_ref',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(give_each_closeout_its_own_ref, migrations.RunPython.noop),
        migrations.AddField(
            model_name='runcloseout',
            name='lesson_removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runcloseout',
            name='lesson_removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templatereport',
            name='lesson_ref',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runcloseout',
            name='lesson_to_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TemplateOwnerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(db_index=True, max_length=120)),
                ('text', models.CharField(max_length=300)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
